name: task 1
run-name: ${{ github.actor }} is testing out test 1
on: [push]
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
      - run: python3 main.py
      - run: python3 test.py
